<?php

namespace AIAnalysisEngine\Inference\DTO;

enum ReasonCode: string
{
    case HIGHER_PRIORITY = 'HIGHER_PRIORITY';
    case LOWER_CONFIDENCE = 'LOWER_CONFIDENCE';
    case VISIBILITY_RESTRICTION = 'VISIBILITY_RESTRICTION';
    case DUPLICATE_RULE = 'DUPLICATE_RULE';
    case MERGED_RELATIONSHIP = 'MERGED_RELATIONSHIP';
    case EXPANDED_GRAPH = 'EXPANDED_GRAPH';
    case FALLBACK_RULE = 'FALLBACK_RULE';
    case DEFAULT_MATCH = 'DEFAULT_MATCH';
}
